### ISSUE TITLE
Missing binding.gyp?

### ISSUE THREAD

**Issue by RSully** [tjfontaine/node-purple#1]
I'm trying to add Ubuntu/linux support to this project and I keep hitting an issue when I try to run any of the files:

```
user@ubuntu-node-purple:~/purple2$ node example.js 

/home/user/purple2/node_modules/ref/node_modules/bindings/bindings.js:91
  throw err
        ^
Error: Could not locate the bindings file. Tried:
 → /home/user/purple2/node_modules/ref/build/binding.node
 → /home/user/purple2/node_modules/ref/build/Debug/binding.node
 → /home/user/purple2/node_modules/ref/build/Release/binding.node
 → /home/user/purple2/node_modules/ref/out/Debug/binding.node
 → /home/user/purple2/node_modules/ref/Debug/binding.node
 → /home/user/purple2/node_modules/ref/out/Release/binding.node
 → /home/user/purple2/node_modules/ref/Release/binding.node
 → /home/user/purple2/node_modules/ref/build/default/binding.node
 → /home/user/purple2/node_modules/ref/compiled/0.6.19/linux/x64/binding.node
    at bindings (/home/user/purple2/node_modules/ref/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/home/user/purple2/node_modules/ref/lib/ref.js:5:47)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:32)
    at Function._load (module.js:311:12)
    at Module.require (module.js:359:17)
    at require (module.js:375:17)
    at Object.<anonymous> (/home/user/purple2/node_modules/ffi/lib/ffi.js:6:11)
    at Module._compile (module.js:446:26)
```

After some digging I thought maybe I just had some version issues and needed to `npm rebuild`, and I even tried reinstalling nodejs. Neither seems to fix the issue. 

After looking at [this](https://github.com/TooTallNate/node-gyp#the-bindinggyp-file) it looks like maybe you would have written this file manually and might not have included it.

If you could point me in the right direction it would be much appreciated.

**Comment by RSully** [comment]
Looks like I had to cd into each of the node_modules and manually `configure` and `build` via `node-gyp`. Didn't realize it.
