### ISSUE TITLE
_pointer is apperently undefined in types.PurpleEventLoopUiOps

### ISSUE THREAD

**Issue by lan17** [tjfontaine/node-purple#2]
Hello.  I am trying to use your library in ubuntu.  I get following error when trying to execute the example.js:

entheogen@debian:~/chatlogs/node/node_modules/purple$ node example.js 

/home/entheogen/chatlogs/node/node_modules/purple/lib/eventloop.js:112
event_loop_ui._pointer.fill(0);
                       ^
TypeError: Cannot call method 'fill' of undefined
    at Object.<anonymous> (/home/entheogen/chatlogs/node/node_modules/purple/lib/eventloop.js:112:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/entheogen/chatlogs/node/node_modules/purple/purple.js:30:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
entheogen@debian:~/chatlogs/node/node_modules/purple$ 

What is the _pointer variable and why is it missing?

**Comment by johndbritton** [comment]
@tjfontaine I'm trying to get your example to run and I'm hitting this error as well. Would appreciate any guidance you can share.
